import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  route(
    ".well-known/appspecific/com.chrome.devtools.json",
    "routes/well-known.chrome-devtools.tsx",
  ),
  route("/", "routes/_app-layout.tsx", [
    index("routes/home.tsx"),
    route("login", "routes/login.tsx"),
    route("cadastro", "routes/cadastro.tsx"),
    route("termos/:slug", "routes/termos.$slug.tsx"),
    route("auth/esqueci-senha", "routes/auth.esqueci-senha.tsx"),
    route("auth/redefinir-senha", "routes/auth.redefinir-senha.tsx"),
    route("agenda", "routes/agenda.tsx"),
    route("campanha/:contractRequestId", "routes/campanha.$contractRequestId.tsx"),
    route("mapa", "routes/mapa.tsx"),
    route("marketplace", "routes/marketplace.tsx"),
    route("dashboard", "routes/dashboard.tsx"),
    route("campanhas", "routes/campanhas.tsx"),
    route("criar", "routes/criar.tsx"),
    route("ofertas", "routes/ofertas.tsx"),
    route("ofertas/criar", "routes/ofertas.criar.tsx"),
    route("ofertas/:id", "routes/ofertas.$id.tsx"),
    route("chat", "routes/chat.tsx"),
    route("perfil", "routes/perfil.tsx"),
    route("indicacoes", "routes/indicacoes.tsx"),
    route("indicacoes/todas", "routes/indicacoes.todas.tsx"),
    route("criador/:creatorId", "routes/criador.$creatorId.tsx"),
    route("configuracoes", "routes/configuracoes.tsx"),
    route("oportunidades", "routes/oportunidades.tsx"),
    route("oportunidades/:id", "routes/oportunidades.$id.tsx"),
    route("pagamento/sucesso", "routes/pagamento.sucesso.tsx"),
    route("pagamento/falhou", "routes/pagamento.falhou.tsx"),
    route("pagamento/aguardando", "routes/pagamento.aguardando.tsx"),
    route("pagamento/pendente", "routes/pagamento.pendente.tsx"),
    route("pagamento/:contractRequestId", "routes/pagamento.$contractRequestId.tsx"),
    route("financeiro", "routes/financeiro.tsx"),
    route("ganhos", "routes/ganhos.tsx"),
    route("carteira", "routes/carteira.tsx"),
  ])
] satisfies RouteConfig;
