// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/mapa": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/perfil": {
    params: {};
  };
  "/criador/:creatorId": {
    params: {
      "creatorId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/register" | "/mapa" | "/dashboard" | "/perfil" | "/criador/:creatorId";
  };
  "routes/_app-layout.tsx": {
    id: "routes/_app-layout";
    page: "/" | "/auth/login" | "/auth/register" | "/mapa" | "/dashboard" | "/perfil" | "/criador/:creatorId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/mapa.tsx": {
    id: "routes/mapa";
    page: "/mapa";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/perfil.tsx": {
    id: "routes/perfil";
    page: "/perfil";
  };
  "routes/criador.$creatorId.tsx": {
    id: "routes/criador.$creatorId";
    page: "/criador/:creatorId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_app-layout": typeof import("./app/routes/_app-layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.register": typeof import("./app/routes/auth.register.tsx");
  "routes/mapa": typeof import("./app/routes/mapa.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/perfil": typeof import("./app/routes/perfil.tsx");
  "routes/criador.$creatorId": typeof import("./app/routes/criador.$creatorId.tsx");
};