// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/cadastro": {
    params: {};
  };
  "/auth/esqueci-senha": {
    params: {};
  };
  "/auth/redefinir-senha": {
    params: {};
  };
  "/agenda": {
    params: {};
  };
  "/empresa/:companyUserId": {
    params: {
      "companyUserId": string;
    };
  };
  "/campanha/:contractRequestId": {
    params: {
      "contractRequestId": string;
    };
  };
  "/mapa": {
    params: {};
  };
  "/marketplace": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/campanhas": {
    params: {};
  };
  "/criar": {
    params: {};
  };
  "/ofertas": {
    params: {};
  };
  "/ofertas/criar": {
    params: {};
  };
  "/ofertas/:id": {
    params: {
      "id": string;
    };
  };
  "/chat": {
    params: {};
  };
  "/perfil": {
    params: {};
  };
  "/indicacoes": {
    params: {};
  };
  "/indicacoes/todas": {
    params: {};
  };
  "/criador/:creatorId": {
    params: {
      "creatorId": string;
    };
  };
  "/configuracoes": {
    params: {};
  };
  "/oportunidades": {
    params: {};
  };
  "/oportunidades/:id": {
    params: {
      "id": string;
    };
  };
  "/pagamento/sucesso": {
    params: {};
  };
  "/pagamento/falhou": {
    params: {};
  };
  "/pagamento/aguardando": {
    params: {};
  };
  "/pagamento/:contractRequestId": {
    params: {
      "contractRequestId": string;
    };
  };
  "/financeiro": {
    params: {};
  };
  "/ganhos": {
    params: {};
  };
  "/carteira": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/.well-known/appspecific/com.chrome.devtools.json" | "/login" | "/cadastro" | "/auth/esqueci-senha" | "/auth/redefinir-senha" | "/agenda" | "/empresa/:companyUserId" | "/campanha/:contractRequestId" | "/mapa" | "/marketplace" | "/dashboard" | "/campanhas" | "/criar" | "/ofertas" | "/ofertas/criar" | "/ofertas/:id" | "/chat" | "/perfil" | "/indicacoes" | "/indicacoes/todas" | "/criador/:creatorId" | "/configuracoes" | "/oportunidades" | "/oportunidades/:id" | "/pagamento/sucesso" | "/pagamento/falhou" | "/pagamento/aguardando" | "/pagamento/:contractRequestId" | "/financeiro" | "/ganhos" | "/carteira";
  };
  "routes/well-known.chrome-devtools.tsx": {
    id: "routes/well-known.chrome-devtools";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/_app-layout.tsx": {
    id: "routes/_app-layout";
    page: "/" | "/login" | "/cadastro" | "/auth/esqueci-senha" | "/auth/redefinir-senha" | "/agenda" | "/empresa/:companyUserId" | "/campanha/:contractRequestId" | "/mapa" | "/marketplace" | "/dashboard" | "/campanhas" | "/criar" | "/ofertas" | "/ofertas/criar" | "/ofertas/:id" | "/chat" | "/perfil" | "/indicacoes" | "/indicacoes/todas" | "/criador/:creatorId" | "/configuracoes" | "/oportunidades" | "/oportunidades/:id" | "/pagamento/sucesso" | "/pagamento/falhou" | "/pagamento/aguardando" | "/pagamento/:contractRequestId" | "/financeiro" | "/ganhos" | "/carteira";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/cadastro.tsx": {
    id: "routes/cadastro";
    page: "/cadastro";
  };
  "routes/auth.esqueci-senha.tsx": {
    id: "routes/auth.esqueci-senha";
    page: "/auth/esqueci-senha";
  };
  "routes/auth.redefinir-senha.tsx": {
    id: "routes/auth.redefinir-senha";
    page: "/auth/redefinir-senha";
  };
  "routes/agenda.tsx": {
    id: "routes/agenda";
    page: "/agenda";
  };
  "routes/empresa.$companyUserId.tsx": {
    id: "routes/empresa.$companyUserId";
    page: "/empresa/:companyUserId";
  };
  "routes/campanha.$contractRequestId.tsx": {
    id: "routes/campanha.$contractRequestId";
    page: "/campanha/:contractRequestId";
  };
  "routes/mapa.tsx": {
    id: "routes/mapa";
    page: "/mapa";
  };
  "routes/marketplace.tsx": {
    id: "routes/marketplace";
    page: "/marketplace";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/campanhas.tsx": {
    id: "routes/campanhas";
    page: "/campanhas";
  };
  "routes/criar.tsx": {
    id: "routes/criar";
    page: "/criar";
  };
  "routes/ofertas.tsx": {
    id: "routes/ofertas";
    page: "/ofertas";
  };
  "routes/ofertas.criar.tsx": {
    id: "routes/ofertas.criar";
    page: "/ofertas/criar";
  };
  "routes/ofertas.$id.tsx": {
    id: "routes/ofertas.$id";
    page: "/ofertas/:id";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/chat";
  };
  "routes/perfil.tsx": {
    id: "routes/perfil";
    page: "/perfil";
  };
  "routes/indicacoes.tsx": {
    id: "routes/indicacoes";
    page: "/indicacoes";
  };
  "routes/indicacoes.todas.tsx": {
    id: "routes/indicacoes.todas";
    page: "/indicacoes/todas";
  };
  "routes/criador.$creatorId.tsx": {
    id: "routes/criador.$creatorId";
    page: "/criador/:creatorId";
  };
  "routes/configuracoes.tsx": {
    id: "routes/configuracoes";
    page: "/configuracoes";
  };
  "routes/oportunidades.tsx": {
    id: "routes/oportunidades";
    page: "/oportunidades";
  };
  "routes/oportunidades.$id.tsx": {
    id: "routes/oportunidades.$id";
    page: "/oportunidades/:id";
  };
  "routes/pagamento.sucesso.tsx": {
    id: "routes/pagamento.sucesso";
    page: "/pagamento/sucesso";
  };
  "routes/pagamento.falhou.tsx": {
    id: "routes/pagamento.falhou";
    page: "/pagamento/falhou";
  };
  "routes/pagamento.aguardando.tsx": {
    id: "routes/pagamento.aguardando";
    page: "/pagamento/aguardando";
  };
  "routes/pagamento.$contractRequestId.tsx": {
    id: "routes/pagamento.$contractRequestId";
    page: "/pagamento/:contractRequestId";
  };
  "routes/financeiro.tsx": {
    id: "routes/financeiro";
    page: "/financeiro";
  };
  "routes/ganhos.tsx": {
    id: "routes/ganhos";
    page: "/ganhos";
  };
  "routes/carteira.tsx": {
    id: "routes/carteira";
    page: "/carteira";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/well-known.chrome-devtools": typeof import("./app/routes/well-known.chrome-devtools.tsx");
  "routes/_app-layout": typeof import("./app/routes/_app-layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/cadastro": typeof import("./app/routes/cadastro.tsx");
  "routes/auth.esqueci-senha": typeof import("./app/routes/auth.esqueci-senha.tsx");
  "routes/auth.redefinir-senha": typeof import("./app/routes/auth.redefinir-senha.tsx");
  "routes/agenda": typeof import("./app/routes/agenda.tsx");
  "routes/empresa.$companyUserId": typeof import("./app/routes/empresa.$companyUserId.tsx");
  "routes/campanha.$contractRequestId": typeof import("./app/routes/campanha.$contractRequestId.tsx");
  "routes/mapa": typeof import("./app/routes/mapa.tsx");
  "routes/marketplace": typeof import("./app/routes/marketplace.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/campanhas": typeof import("./app/routes/campanhas.tsx");
  "routes/criar": typeof import("./app/routes/criar.tsx");
  "routes/ofertas": typeof import("./app/routes/ofertas.tsx");
  "routes/ofertas.criar": typeof import("./app/routes/ofertas.criar.tsx");
  "routes/ofertas.$id": typeof import("./app/routes/ofertas.$id.tsx");
  "routes/chat": typeof import("./app/routes/chat.tsx");
  "routes/perfil": typeof import("./app/routes/perfil.tsx");
  "routes/indicacoes": typeof import("./app/routes/indicacoes.tsx");
  "routes/indicacoes.todas": typeof import("./app/routes/indicacoes.todas.tsx");
  "routes/criador.$creatorId": typeof import("./app/routes/criador.$creatorId.tsx");
  "routes/configuracoes": typeof import("./app/routes/configuracoes.tsx");
  "routes/oportunidades": typeof import("./app/routes/oportunidades.tsx");
  "routes/oportunidades.$id": typeof import("./app/routes/oportunidades.$id.tsx");
  "routes/pagamento.sucesso": typeof import("./app/routes/pagamento.sucesso.tsx");
  "routes/pagamento.falhou": typeof import("./app/routes/pagamento.falhou.tsx");
  "routes/pagamento.aguardando": typeof import("./app/routes/pagamento.aguardando.tsx");
  "routes/pagamento.$contractRequestId": typeof import("./app/routes/pagamento.$contractRequestId.tsx");
  "routes/financeiro": typeof import("./app/routes/financeiro.tsx");
  "routes/ganhos": typeof import("./app/routes/ganhos.tsx");
  "routes/carteira": typeof import("./app/routes/carteira.tsx");
};