// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/empresa": {
    params: {};
  };
  "/criadora": {
    params: {};
  };
  "/jobs/novo": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/empresa" | "/criadora" | "/jobs/novo";
  };
  "routes/_app-layout.tsx": {
    id: "routes/_app-layout";
    page: "/" | "/auth/login" | "/empresa" | "/criadora" | "/jobs/novo";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/business.dashboard.tsx": {
    id: "routes/business.dashboard";
    page: "/empresa";
  };
  "routes/creator.dashboard.tsx": {
    id: "routes/creator.dashboard";
    page: "/criadora";
  };
  "routes/jobs.new.tsx": {
    id: "routes/jobs.new";
    page: "/jobs/novo";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_app-layout": typeof import("./app/routes/_app-layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/business.dashboard": typeof import("./app/routes/business.dashboard.tsx");
  "routes/creator.dashboard": typeof import("./app/routes/creator.dashboard.tsx");
  "routes/jobs.new": typeof import("./app/routes/jobs.new.tsx");
};